### ISSUE TITLE
Desired updating of Capcha

### ISSUE THREAD

**Issue by martin03** [tomatocart/TomatoCart-v1#288]
I recently had a breakthrough of spamming emails through the contact form.
Download the latest version from:
[https://www.phpcaptcha.org/download/](url)
And unzip the folder.
Go to folder:
ext /
and replace a folder:
securimage
with the new unpacked folder:
securimage
Good luck

**Comment by kreossino** [comment]
i test it now
thank you

**Comment by bwon** [comment]
Cheers seems to work good
